version: '1.0'

services:
  api:
    container_name: nest-service-demo
    depends_on:
      - postgres
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT${POSTGRES_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # - REDIS_HOST:=${REDIS_HOST}
      # - REDIS_PORT=${REDIS_PORT}
      # - REDIS_USERNAME:default
      # - REDIS_PASSWORD:fbX4PgCelRue3exBCWFETglpCkrzehiB

    ports:
      - 3000:3001
    command: yarn run start:dev
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
